### PR TITLE
[+] Added cheonwoomaeng

### PR DESCRIPTION
**Pull request by Paranoid-Pufferfish**

### CODE REVIEW

**Comment by Twinsherry** [comment]
需要同时构建简体中文页面及繁体中文页面。您可以在中国语页面使用日本语文本。

簡体字中国語ページと繁体字中国語ページの両方を作成する必要があります。中国語ページで日本語テキストを使用できます。

**Comment by Twinsherry** [comment]
必要なディレクトリ構造は次のとおりです：
name
│  info.yml
│  page.en.md
│  page.md
│  page.zh_hant.md
│  
└─photos
        profile.png

**Comment by Twinsherry** [comment]
第一言語が日本語である場合は、二次翻訳による誤差を防ぐために、日本語のテキストを提供することができます。

**Comment by Paranoid-Pufferfish** [comment]
我的主要语言实际上是英语，因为我不会说中文或日语^^´´

**Comment by Paranoid-Pufferfish** [comment]
我不知道为什么会失败，我使用谷歌翻译来制作中文版。抱歉

**Comment by Paranoid-Pufferfish** [comment]
好的，谢谢！再次抱歉，这是我第一次投稿

**Comment by Twinsherry** [comment]
---
name: Ryu
info:
    alias: Rio, Yotaro
    location: 日本
---

information like this~

**Comment by Paranoid-Pufferfish** [comment]
> ## name: Ryu
> info:
> alias: Rio, Yotaro
> location: 日本
> 
> information like this~

Understood! it turns out i accidently translated the YAML header too, my bad

**Comment by Twinsherry** [comment]
Can the region be precise to the prefectures of Japan?
Eg：日本东京 日本北海道 日本京都

**Comment by Paranoid-Pufferfish** [comment]
> Can the region be precise to the prefectures of Japan? Eg：日本东京 日本北海道 日本京都

I will have to ask her family members because im not sure

**Comment by Twinsherry** [comment]
此外，id需要与目录名称相同。
现id：cheonwoomaeng 
现目录名称：rio_kang
需要修改

In addition, the ID needs to be the same as the directory name.
Current ID: cheonwoomaeng 
Current directory name: rio_kang
also need to fix this

**Comment by LS-KR** [comment]
先别折腾了

把主要文本修好窝明天修构建

**Comment by Paranoid-Pufferfish** [comment]
Alright thanks a lot!, from the logs it seems like the build fails at "qiqi233345"'s comments, i dont know why as i didnt touch them

**Comment by Twinsherry** [comment]
Google Translate should bear 100% responsibility for the failure of  construction
谷歌生草机全责

**Comment by Paranoid-Pufferfish** [comment]
Omg I just noticed it. Thanks a lot friends!!

**Review by LS-KR — APPROVED** [review]

**Review by Twinsherry — APPROVED** [review]

**Comment by Twinsherry** [comment]
She put _ASIJ '25_ in her straw page. ASIJ means The American School in Japan. I think her location was Tokyo, Japan.
But I think maybe we should ask her sister for approved to show this information on her profile card( Although Tokyo is such a big city so it doesn't matter )
I will merge this pull request first, if you want to modify more of this entry, please contact us by comment here~

我看到她在 straw 页面写了 ASIJ 25'，ASIJ 是日本美国国际学校的意思，在日本东京。不过我觉得写上去这个可能要征求她妹妹同意（虽然东京是个大城市也许不要紧）。我先合并这个 PR 了，如果还有需要修改的，可以在这里留评论联系我们~

**Comment by Paranoid-Pufferfish** [comment]
Hello !!! So yeah I just contacted her family members, and she is indeed lives in Tokyo(Originally Okinawa), and yes you can add it, thanks a lot ^^

**Comment by Twinsherry** [comment]
> Hello !!! So yeah I just contacted her family members, and she is indeed lives in Tokyo(Originally Okinawa), and yes you can add it, thanks a lot ^^

Thanks you and we will remember she and her story forever.

**Pull request merged**
