### PR TITLE
[+] dogesir

### PR DESCRIPTION
**Pull request by RinLin-NYA**

### CODE REVIEW

**Comment by RinLin-NYA** [comment]
The newest commits is a statement of my fork. Sorry if it brings difficulty to any developers.

**Comment by sauricat** [comment]
Thank you for your contribution! There are just some subtle phrasing problems we may need you to resolve. To protect our readers, we have to do a responsible suicide report. Therefore, the detail of methods or drugs shouldn't be depicted in the article. Also, we should not glorify suicide attempts or suicidal thoughts too much. Although I also appreciate the metaphor of the galaxy train, we need to keep it just on a metaphorical level.

If you need any help revising the article, please feel free to comment. Both Chinese and English are okay. 

See also: WHO Preventing Suicide Guide ([Simplified Chinese version](https://apps.who.int/iris/bitstream/handle/10665/208279/9789290617488_chi.pdf) available).

> 「虽然我活着也很痛苦，不知道意义何在，但是我知道尽力挽回别人的生命一定不会后悔。」—— 倉山静葉

Best wishes.

**Comment by RinLin-NYA** [comment]
> Thank you for your contribution! There are just some subtle phrasing problems we may need you to resolve. To protect our readers, we have to do a responsible suicide report. Therefore, the detail of methods or drugs shouldn't be depicted in the article. Also, we should not glorify suicide attempts or suicidal thoughts too much. Although I also appreciate the metaphor of the galaxy train, we need to keep it just on a metaphorical level.
> 
> If you need any help revising the article, please feel free to comment. Both Chinese and English are okay.
> 
> See also: WHO Preventing Suicide Guide ([Simplified Chinese version](https://apps.who.int/iris/bitstream/handle/10665/208279/9789290617488_chi.pdf) available).
> 
> > 「虽然我活着也很痛苦，不知道意义何在，但是我知道尽力挽回别人的生命一定不会后悔。」—— 倉山静葉
> 
> Best wishes.

Thank you for your remind. I will close my pull request now and modify the context later.

**Comment by RinLin-NYA** [comment]
啊说回来我接下来还是用回中文吧(悲

**Pull request closed without merging**
